on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
          
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{steps.version.outputs.full_without_prefix}}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release ${{steps.version.outputs.full_without_prefix}}" \
              --generate-notes \
              ${{ steps.version.outputs.is_stable != 'true' && '--prerelease' || '' }}
