name: Tests

on: [pull_request]

jobs:
  typescript:
    name: Type Validation
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        uses: kitbagjs/actions-setup-project@main

      - name: Validate types
        run: npm run types

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        uses: kitbagjs/actions-setup-project@main

      - name: Run unit tests
        run: npm run test